### ISSUE TITLE
Change truthy conditional to verify the initialValue of a FormGroup

### ISSUE THREAD

**Issue by LauraBeatris** [jungsoft/formup#11]
[The following conditional](https://github.com/jungsoft/formup/blob/bbdab083fc2c3ad288950ea8ce6e89d55662253e/packages/core/src/contexts/FormGroupContext/FormGroupContainer.tsx#L41)  inside of the `FormGroupContainer` is not allowing to set falsy values like ```false``` or ```0``` as the initialValue.

```
  React.useEffect(() => {
    if (initialValue) {
      setFormGroupValue(initialValue);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```

For instance, passing a ```false``` value to a FormGroup will lead to that behavior: 

<img width="267" alt="Screen Shot 2020-05-11 at 16 19 15" src="https://user-images.githubusercontent.com/48022589/81602555-35377280-93a3-11ea-9de6-c3fe02f35cf0.png">

Notice that the value is null because it wasn't set in the context. 

The ```FormGroupContext``` should verify if the initialValue isn't `undefined`, `null` or `empty strings`

**Comment by pedro-lb** [comment]
PR in review

**Comment by pedro-lb** [comment]
Release https://github.com/jungsoft/formup/releases/tag/1.2.21
