### ISSUE TITLE
Feature: Add transformOnSubmit option to useFormup

### ISSUE THREAD

**Issue by pedro-lb** [jungsoft/formup#29]
Currently, any `.transform` functions declared in yup schema do not mutate the form value, as [described in the yup documentation](https://github.com/jquense/yup#mixedtransformcurrentvalue-any-originalvalue-any--any-schema).

However, we still need to filter these values when submitting the form, even though the `.transform` is already declared on the schema, we still have to duplicate code to transform it before submitting.

An example is a component that uses `react-select`, which keeps an object in the value, e.g. `{ value, label }`.

We could have an option, `transformOnSubmit`, passed to `useFormup`'s options (default false), that if true would apply the transformations to the object before passing it to `onSubmit` callback`.

**Comment by gabrielnaoto** [comment]
Please, these makes a lot of sense, because we can have a really single source of truth. 

Then the form itself would hold the raw data values (to be used in date pickers, selects, and others), and formup would validate and transform it into the proper schema.

**Comment by pedro-lb** [comment]
Released in https://github.com/jungsoft/formup/releases/tag/1.6.0
