### ISSUE TITLE
Pass label from schema to the custom input props

### ISSUE THREAD

**Issue by gabrielnaoto** [jungsoft/formup#30]
The custom inputs should receive the `label` defined in the schema, without we having to define it in the form

```js
<FormInput
  name="operator_id"
  component={Selector}
  injectFormupData={true}
  label="A label goes here" // <- This shouldn't be necessary, only if we need to override
/>

**Comment by pedro-lb** [comment]
Looks good! We should be able to override it by passing a prop to `FormInput`, but it should pass `label` (as defined in schema) by default 🚀

**Comment by pedro-lb** [comment]
PR https://github.com/jungsoft/formup/pull/31

**Comment by pedro-lb** [comment]
While we're at it, let's also add `aria-label` injection, to keep our inputs accessibility-friendly

**Comment by pedro-lb** [comment]
https://github.com/jungsoft/formup/releases/tag/1.4.0
