### ISSUE TITLE
Pass custom props to FormInput component

### ISSUE THREAD

**Issue by pedro-lb** [jungsoft/formup#5]
When rendering a component using `FormInput`, such as:

```js
const CustomInput = (props) => (
  <input {...props} />
);

...

<FormInput name="" component={CustomInput} />
```

We should have access to more information, such as the error message (if any). Currently `formup` only passes an `error` prop, boolean.

Problem: if we inject other properties into `input` (such as `errorMessage`), React will throw an error since `errorMessage` is not an `input` property.

**Comment by pedro-lb** [comment]
Maybe we could pass in an object containing all extra information (such as `formupData`).

This would have to be handled at every component passed into `component` prop of `FormInput` to avoid console errors, since `formupData` can't be injected into `input`.

That means this issue would create a breaking change.

**Comment by pedro-lb** [comment]
In order to avoid a release containing breaking changes we could add two props in `FormInput`: `injectFormupData` (default false) and `formupData`.

If `injectFormupData` is true, it would inject the `formupData` prop and we would have to handle it in the component.

Otherwise it wouldn't be necessary to change anything to already existing code that depends on formup.

**Comment by gabrielnaoto** [comment]
I like this approach! Then, if we want to handle custom formup data like errors we just need to enable `injectFormupData`, but we must clarify that we have to handle the `formupData` prop must not be passed on to the final input.

**Comment by pedro-lb** [comment]
I think that's our solution right there

**Comment by pedro-lb** [comment]
Looking into this

https://github.com/jungsoft/formup/tree/feature/pass-custom-props-to-forminput-component-5

**Comment by pedro-lb** [comment]
Waiting for review

https://github.com/jungsoft/formup/pull/6/files

**Comment by gabrielpra1** [comment]
I think we should create an issue for version 2, so we can keep track of all breaking changes and when we have enough of them we could release a new version without these workarounds to maintain backwards compatibility

**Comment by pedro-lb** [comment]
@gabrielpra1 

There won't be any breaking changes in this new release

**Comment by pedro-lb** [comment]
@gabrielpra1 

I've created a milestone for V2 so that we can link all issues that contain breaking changes:

https://github.com/jungsoft/formup/milestone/1

**Comment by gabrielpra1** [comment]
Cool, even better then! 😄

**Comment by pedro-lb** [comment]
The kraken was released

https://github.com/jungsoft/formup/releases/tag/1.2.17
